### ISSUE TITLE
close event emitted twice

### ISSUE THREAD

**Issue by hueniverse** [hapijs/nigel#25]

**Comment by hueniverse** [comment]
@cjihrig is there a more elegant solution for dual v12/14 node support?

**Comment by cjihrig** [comment]
Untested, but would passing `emitClose` or `autoDestroy` when constructing the stream give the behavior you're looking for across versions?

**Comment by hueniverse** [comment]
The docs say that `emitClose` has no impact on `Writeable`. Didn't test `autoDestroy`.

**Comment by cjihrig** [comment]
Is there a failing test in this repo? I ran the nigel tests locally on Node 12 and Node 14 with 1215978829bd444fca935d61bd5a6dbd6cb793bb (removing your recent fixes for this issue) and everything passed.

**Comment by hueniverse** [comment]
The tests pass because of how lab uses promises. Before it was detecting double `done()` but now it just get ignored. So the master tests don't show that `close` is emitted twice...

**Comment by cjihrig** [comment]
Proposed fix with a test in https://github.com/hapijs/nigel/pull/26.
